---
title: "Search and pragmatics in Connector"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

# Imports

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(ggthemes)
setwd('/Users/abhilashakumar/connector-pragmatics-search')
targets = read_csv("data/targets.csv") %>% select(wordpair, Level)
```

```{r}
softmax_t = function (x, tau){
  e_x = exp(x*tau)
  axis_sum = sum(e_x)
  return (e_x / axis_sum)
}
```

# E1: online candidate study

We compare the candidates generated by the models with the candidates generated by participants in a study.

```{r}
setwd('data/exp1')
e1 = read_csv("e1_common_candidates.csv") %>%
  mutate(Level = fct_relevel(Level, "easy", "medium","hard"))%>%
      mutate(budget = as.numeric(gsub("[^0-9.-]", "", budget)))
```

## overall common candidates

```{r}
common_candidates= e1 %>% rowwise()%>%
  mutate(prop_common_union = len_union_common/len_cluelist_behavioral,
    prop_common_intersection = len_intersection_common/len_cluelist_behavioral) %>%
  pivot_longer(names_to = "model", cols = prop_common_union:prop_common_intersection)%>%
  separate(model, into = c("prop", "index", "model")) %>% select(-c(prop,index))

e1plot = common_candidates %>% 
  group_by(Level, budget, model) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
ggplot(aes(x = budget, y = mean, color = model, group = model)) +
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.2, 
                color = "gray", position = position_dodge(0))+
  geom_line()+
  geom_point(size = 2)+
  facet_wrap(~Level)+
    labs(y = 'common candidates (proportion)', 
         title = "proportion of common candidates with behavioral data") +
  scale_color_calc()+
  theme_few() +
  theme(aspect.ratio = 1, legend.position = c(0.85, 0.2)) 

ggsave("../../analysis/plots/exp1_plot1.pdf", e1plot)

```

## final clue

```{r}
e1_finalclue = e1 %>% select(clueGiverID, Level, wordpair, clueFinal, 
                              budget, finalclue_index_union, finalclue_index_intersection) %>%
  pivot_longer(names_to = "model", cols = finalclue_index_union:finalclue_index_intersection) %>%
  separate(model, into = c("finalclue", "index", "model")) %>% select(-c(finalclue,index))%>%
  # set -1 to the lowest visitation frequency and take proportion for others
  # value == 1 means most visited node, value == 0 means not visited at all
  mutate(value = ifelse(value == -1, 0, (12218-value)/12218))

e1plot2 = e1_finalclue %>% 
  group_by(budget, model) %>%
  summarise(ci = list(mean_cl_boot(value) %>% 
                        rename(mean=y, lwr=ymin, upr=ymax))) %>% unnest%>%
  ggplot(aes(x = budget, y = mean, color = model, group = model)) +
  geom_errorbar(aes(ymin=lwr, ymax=upr), size = 0.5, width=.2, 
                color = "gray", position = position_dodge(0))+
  geom_line()+
  geom_point(size = 2)+
  labs(y = 'mean visitation proportion for final clue', 
       title = "proportion of final clue visitation") +
  theme_few() +
  scale_color_calc()+
  theme(aspect.ratio = 1, 
          legend.position = c(0.85, 0.2)) 
ggsave("../../analysis/plots/exp1_plot2.pdf", e1plot2)
```


# E2: speaker selections
```{r}
setwd('../../data/exp2')

e2_clues = read_csv("e2_corrected.csv") %>% 
  mutate(wordpair = gsub(' - ', '-', wordpair)) %>%
  rename(clue = correctedClue)%>%
  distinct()%>%
  select(wordpair, clue, clueCount, Level)

search = read_csv("scores.csv") %>%
  pivot_longer(names_to = "model", cols = union2:intersection512)%>%
  rename(clue = correctedClue)%>%
  separate(model, into = c("type", "budget"), "(?<=[a-z])(?=[0-9])")%>%
  mutate(value = value/1000)
```



## overall patterns

```{r}
e2_search =search %>%
    mutate(model= "walk-only", alpha = "walk-only",
           wordpair = gsub('\\s+', '', wordpair))%>%
  select(wordpair, boardnames, budget, clue, model, alpha, type, value )
max(e2_search$value)

e2_nonRSA = read_csv("nonRSAprobs.csv") %>% mutate(model = "nonRSA", alpha = as.character(alpha)) 
e2_RSA = read_csv("RSAprobs.csv") %>% mutate(model = "RSA", alpha = "RSA")

e2_nonRSA_RSA = rbind(e2_RSA, e2_nonRSA) %>%
  rename(union = clue_probs_union, intersection = clue_probs_intersection)%>%
  pivot_longer(names_to = "type", cols = union:intersection)

e2_combined_models = rbind(e2_search, e2_nonRSA_RSA) %>%
  left_join(e2_clues) %>%
  mutate(LL = log(value)*clueCount,
         budget = as.numeric(gsub("[^0-9.-]", "", budget)))

# histogram
e2_combined_models %>%
  ggplot(aes(x = LL, group = model, fill = model)) +
  geom_histogram(binwidth = 50) + theme_few()

e2_sumLL = e2_combined_models %>% 
  group_by(alpha, budget, type)%>%
  summarize_at(vars(LL), sum)
  
e2_plot = e2_sumLL %>%
  ggplot(aes(x = budget, y = LL, color = alpha, group = alpha)) +
  geom_point(size = 2)+
  geom_line()+
  facet_wrap(~type)+
    labs(y = 'log likelihood', title = "E2: model likelihoods") +
    theme_few() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
         aspect.ratio = 1.5) 

ggsave("../../analysis/plots/exp2_plot.pdf", e2_plot)

```
## item analysis
```{r}
e2_behavioral = e2_clues %>% select(wordpair, clue, clueCount) %>%
  group_by(wordpair) %>%
  slice_max(clueCount) %>% group_by(wordpair) %>% slice(1) %>%
  mutate(model = "behavioral") %>% select(wordpair, model, clue)

e2_top_predictions = e2_combined_models %>%
  group_by(wordpair, model) %>%
  slice_max(value)%>%
  group_by(wordpair, model) %>%
  slice(1) %>% select(wordpair, model, clue) %>%
  rbind(e2_behavioral)%>%
  pivot_wider(names_from = model, values_from = clue)

e2_top_predictions %>%
  mutate(walk_score = ifelse(`walk-only` == behavioral, 1,0),
         nonRSA_score = ifelse(nonRSA == behavioral, 1, 0),
         RSA_score = ifelse(RSA == behavioral, 1, 0))  %>%
  pivot_longer(names_to = "score", cols=c(walk_score, nonRSA_score, RSA_score))%>%
  group_by(score)%>%
  summarise_at(vars(value), mean)

## correlation: RSA correlates best with clueCounts
e2_combined_models %>% left_join(targets)%>%
  group_by(model) %>%
  summarize(cor(value, clueCount))
```

# E3: targeted endorsements

```{r}
setwd('../../data/exp3')

e3_data = read_csv("e3_data_corrected.csv") %>% filter(!is.na(wordpair) & accessibility != "prac")%>%
  select(wordpair, correctedClue, sona_id, response, condition)%>%
  mutate(wordpair = gsub(' - ', '-', wordpair),
         response = as.numeric(response))%>%
  group_by(wordpair, correctedClue) %>%
  # sum up all the rating scores, higher sum total means that clue was most preferred
  summarise_at(vars(response), sum)%>%
  rename(clue = correctedClue)
```

## overall patterns

```{r}
e3_search = e3_data %>% select(wordpair, clue) %>% distinct() %>%
  left_join(search)%>% filter(!is.na(value))%>%
      mutate(alpha = "walk-only", model = "walk-only") %>%
  select(wordpair,model, alpha, budget, type, clue, value)

e3_nonRSA = read_csv("e3_nonRSAprobs.csv")%>% mutate(alpha = as.character(alpha), model = "nonRSA")
e3_RSA = read_csv("RSAprobs.csv") %>% mutate(alpha = "RSA", model = "RSA")

e3_RSA_nonRSA = rbind(e3_nonRSA, e3_RSA) %>%
  pivot_longer(names_to = "type", cols = clue_probs_union:clue_probs_intersection) %>%
  separate(type, into=c("cluep","probs", "type")) %>% select(-c(cluep, probs)) %>%
  mutate(alpha = as.character(alpha))%>%
  select(wordpair,model, alpha, budget, type, clue, value)

e3_combined = rbind(e3_search, e3_RSA_nonRSA)%>%
  left_join(e3_data) %>% left_join(targets) %>%
  mutate(budget = as.numeric(gsub("[^0-9.-]", "", budget)),
             LL = log(value)*response)

# histogram

e3_combined %>%
  ggplot(aes(x = LL, group = model, fill = model)) +
  geom_histogram(binwidth = 500) + theme_few()

e3_sumLL =e3_combined %>% 
  group_by(type, alpha, budget) %>%
  summarize(sumLL = sum(LL)) %>%
  arrange(desc(sumLL))

e3_plot = e3_sumLL %>%
  filter(!is.na(type)) %>%
  ggplot(aes(x = budget, y = sumLL, color = alpha, group = alpha)) +
  geom_point(size = 2)+
  geom_line()+
  facet_wrap(~type)+
    labs(y = 'log likelihood', title = "E3: model likelihoods") +
    theme_few() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
         aspect.ratio = 1.5) 

ggsave("../../analysis/plots/exp3_plot.pdf", e3_plot)

```

## item analysis

```{r}
e3_behavioral = e3_data %>% select(wordpair, clue, response) %>%
  group_by(wordpair) %>%
  slice_max(response) %>% group_by(wordpair) %>% slice(1) %>%
  mutate(model = "behavioral") %>% select(wordpair, model, clue)

e3_top_predictions = e3_combined %>%
  group_by(wordpair, model) %>%
  slice_max(LL)%>%
  group_by(wordpair, model) %>%
  slice(1) %>% select(wordpair, model, clue) %>%
  rbind(e3_behavioral)%>%
  pivot_wider(names_from = model, values_from = clue)

e3_top_predictions %>%
  mutate(walk_score = ifelse(`walk-only` == behavioral, 1,0),
         nonRSA_score = ifelse(nonRSA == behavioral, 1, 0),
         RSA_score = ifelse(RSA == behavioral, 1, 0))  %>%
  pivot_longer(names_to = "score", cols=c(walk_score, nonRSA_score, RSA_score))%>%
  group_by(score)%>%
  summarise_at(vars(value), mean)

## correlation: RSA correlates best with clueCounts
e3_combined %>%
  filter(!is.na(value))%>%
  group_by(model) %>%
  summarize(cor(value, response))
```



